version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Fix Cloud SDK GPG Key Issue
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3 || \
            sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys C0BA5CE6DC6315A3
      - run:
          name: Install & Set Java 17
          command: |
            sudo apt update
            sudo apt install openjdk-17-jdk -y
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
      - run:
          name: Verify Java Version
          command: java -version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
