version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Fix Cloud SDK GPG Key Issue
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3 || \
            sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys C0BA5CE6DC6315A3
      - run:
            name: Install OpenJDK 17 from Adoptium
            command: |
              wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
              sudo mkdir -p /usr/lib/jvm
              sudo tar -xvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz -C /usr/lib/jvm
              sudo mv /usr/lib/jvm/jdk-17.0.10+7 /usr/lib/jvm/java-17-adoptium
              echo "export JAVA_HOME=/usr/lib/jvm/java-17-adoptium" >> $BASH_ENV
              echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV
              source $BASH_ENV
              java -version
      - run:
          name: Verify Java Version
          command: java -version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
